<?php

/**
 * Helper function for foreign modules which want to use the Saft.drupal module.
 * This function init the Saft library and its vendors. (autoloading and class inclusion)
 */
function saft_initlib()
{
    require_once 'sites/all/modules/saft/Saft/vendor/autoload.php';
}

/**
 * Implements hook_help().
 */
function Saft_help($path, $arg)
{
    $saftPath = 'sites/all/modules/saft/Saft/vendor/saft';

    // fetch version of Saft and Saft.skeleton
    $saftInfo = json_decode(file_get_contents($saftPath .'/saft/composer.json'), true);
    $saftSkeletonInfo = json_decode(
        file_get_contents($saftPath .'/saft-skeleton/composer.json'),
        true
    );

    // show a simple info page with version info and further links
    switch ($path) {
        case 'admin/help#Saft':
            return 'Info page for Saft library and Saft.skeleton. '.
                'You are running Saft at version <strong>'. $saftInfo['version'] .'</strong> '.
                'and Saft.skeleton at version <strong>'. $saftSkeletonInfo['version'] .'</strong>.'.
                '<br/><br/>Further information:'.
                '<ul><li><a href="https://safting.github.io/">Saft Dokumentation</a></li>'.
                '<li><a href="https://github.com/SaftIng/Saft.example">Saft Examples</a></li></ul>'.
                '<br/><br/>';
    }
}
